sudo: required
dist: xenial
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install tox-travis
script:
- tox
- tox -e lint
deploy:
  provider: pypi
  user: ahmet2mir
  password:
    secure: umCwpeVaC2HNjoKrmeze5RXcT8HJCISKUftVrQST0egA3AkuyMyGmbboCCTZTsEwYwLqZUvNSFsACfy21MmCeosBpZRHAQOj89HUrF/wcRbia8emc70AZLs7bd4+Si7aqOi0GT+I/IS1EK3Hb2BeqbZ/u1em/xyKgpDm2KkJuIrfxJe71T1KXg1uwiz8VqS07U7412O0vKMgsgVBoRiOTi6x20xewp6+5Lf60rIwjb8FmZpk2hlPNM0fJcECi5AXVN1PXZ8l5FCHaHoSzSt4c00vo28a1Yp1uGeF9hK4n+hUWvtHFAMfy2ZD75IDLowMjv+1PKPZH7079WPD5TZqIFTz2CKY+48CTYC4x3gBixn48lyNZYoFXlO08jWeE3BP7DhbbnYhOLG/nT34pJ8D+wmLGTXPrTNSYEdo3sR4frJjqMZOyVACtQADuGFYZX0RLpq+oFV3i39LLSUkc3BCI+5eL9axBFzNoZV5jU56RpnNgGkSbNQD+O9Wxi4EhSh3VL7vFWF2os4Wx/UfFcYpRzKsH2Z+MRr2ZH9Op+ISctDfDvjm9IVXU7YImon82uzNI8T4lY/8WX38vj7c1jOV+ZarWuHnsWr0wJx6x7d6TccXmWGMfK8pX3W7B451HmtcXVajbwRQk0rq+SM7yjAWrE+jiVUG5E4kEc9IWKFsr6M=
  on:
    tags: true
    python: 3.6
